### ISSUE TITLE
Problems compiling under Xcode 4.6

### ISSUE THREAD

**Issue by dmishe** [joshaber/RACSignupDemo#1]
I got all kinds of ARC errors when compiling this, maybe there should be an install guide for the project — which targets are ARC compatible and which are not?

Also it wouldn't hurt to mention that you have to do

```
git submodule update --init --recursive 
```

after clone, I guess it's pretty obvious, but still :)

**Comment by joshaber** [comment]
It sounds like the project was opened before the submodules were cloned, so it didn't find the configuration files.

Try closing the problem and re-opening after `git submodule update --recursive --init`.

**Comment by dmishe** [comment]
Yep that was it, thanks!

**Comment by joshaber** [comment]
No problem!
