### ISSUE TITLE
Demo doesn't compile

### ISSUE THREAD

**Issue by Tylerc230** [joshaber/RACSignupDemo#4]
I cloned the project, installed the submodules and I get many errors when compiling.

**Comment by jspahrsummers** [comment]
Can you share what those errors are?

**Comment by joshaber** [comment]
The app compiles fine for me with a fresh clone. Be sure you ran `git submodule update --recursive --init`.

If it still doesn't compile then please let us know what errors you're seeing.

**Comment by joshaber** [comment]
Closing, but feel free to re-open if there's still an issue.
